### ISSUE TITLE
TypeError: chapterAndVerse is not a function

### ISSUE THREAD

**Issue by MurphyAdam** [danday74/chapter-and-verse#5]
Hello,
I am trying to use chapter-and-verse with my React app, but it would not work and it throws the error "TypeError: chapterAndVerse is not a function".

I am importing the package as in the example:

```javascript 1.7
const chapterAndVerse = require('chapter-and-verse')
let cv = chapterAndVerse('Dan 4:1-3')
```

**Comment by danday74** [comment]
sorry its a bit broken from an import perspective

try importing the correct file in node_modules, something like:

const chapterAndVerse = require('chapter-and-verse/index')

**Comment by MurphyAdam** [comment]
@danday74 Ah, thank you. It's working.
